CREATE TABLE CUSTOMER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE BIGINT NOT NULL,
	CREATED_DATE TIMESTAMP(6),
	UPDATED_DATE TIMESTAMP(6)
); 